#!/usr/bin/env python3
"""GUI entrypoint to Penetrance Estimator."""

import sys
from penestGUI import PenEstAppMain

from PyQt5 import QtWidgets

app = QtWidgets.QApplication(sys.argv)
appmain = PenEstAppMain()
appmain.show()
appmain.raise_()
sys.exit(app.exec_())
